project:
  type: manuscript
  output-dir: docs
  resources:
   - image/**


manuscript:
  article: index.qmd

format:
  html:
    df-print: kable
  pdf: default
  jats: default

execute:
  freeze: true



